// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzqqVpiowDLQsMJtiu8pP1iZIqN6O8_LQ',
    appId: '1:404517674403:web:17888afd271809bc5f0e16',
    messagingSenderId: '404517674403',
    projectId: 'burgerapp-cc15a',
    authDomain: 'burgerapp-cc15a.firebaseapp.com',
    storageBucket: 'burgerapp-cc15a.firebasestorage.app',
    measurementId: 'G-0RL5J0WR42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAWxjhtH9nXlvkUU8yvOLrbx1X_3MyYtY',
    appId: '1:404517674403:android:0f010855bba7aa3d5f0e16',
    messagingSenderId: '404517674403',
    projectId: 'burgerapp-cc15a',
    storageBucket: 'burgerapp-cc15a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNVlQaZ_PzZPwuI6mtlER2w1nucDCU5_M',
    appId: '1:404517674403:ios:8774273dfc15cd8f5f0e16',
    messagingSenderId: '404517674403',
    projectId: 'burgerapp-cc15a',
    storageBucket: 'burgerapp-cc15a.firebasestorage.app',
    iosBundleId: 'com.example.burgerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNVlQaZ_PzZPwuI6mtlER2w1nucDCU5_M',
    appId: '1:404517674403:ios:8774273dfc15cd8f5f0e16',
    messagingSenderId: '404517674403',
    projectId: 'burgerapp-cc15a',
    storageBucket: 'burgerapp-cc15a.firebasestorage.app',
    iosBundleId: 'com.example.burgerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzqqVpiowDLQsMJtiu8pP1iZIqN6O8_LQ',
    appId: '1:404517674403:web:6b00bf87b10ef4765f0e16',
    messagingSenderId: '404517674403',
    projectId: 'burgerapp-cc15a',
    authDomain: 'burgerapp-cc15a.firebaseapp.com',
    storageBucket: 'burgerapp-cc15a.firebasestorage.app',
    measurementId: 'G-5KBVL8BNM4',
  );
}
